services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
    command: >
      bash -c "uv run manage.py migrate
      && uv run manage.py collectstatic --noinput
      && uv run manage.py tailwind install
      && uv run manage.py tailwind start
      && uv run uwsgi --ini tasknote_uwsgi.ini"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www/tasknote
      - workdir:/var/www/tasknote
    networks:
      - private_network
      - public_network

  mysql:
    image: mysql:8.0.41
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 33066:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - private_network

  redis:
    image: redis:6-bookworm
    restart: always
    ports:
      - "63799:6379"
    volumes:
      - redis-data:/data
    networks:
      - private_network

  nginx:
    image: nginx:1-bookworm
    restart: always
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./tasknote.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/tasknote/static
      - workdir:/var/www/tasknote

volumes:
  workdir:
  mysql-data:
  redis-data:

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge
