# Generated by Django 5.1.6 on 2025-04-20 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='id público')),
                ('title', models.CharField(max_length=64, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('is_done', models.BooleanField(default=False, verbose_name='está feito')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID do usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='data de desativação')),
                ('priority', models.IntegerField(choices=[(1, 'alta'), (2, 'média'), (3, 'baixa')], default=1, verbose_name='prioridade')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='data de finalização')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
