from typing import Protocol

from ...domain.entities import Task
from ..dtos import TaskCreateDTO, TaskUpdateDTO


class ITaskService(Protocol):
    def create_task(self, task: TaskCreateDTO) -> Task: ...

    def find_task_by_public_id(self, task_public_id: str) -> Task | None: ...

    def get_user_tasks(self, user_id: int) -> list[Task] | None: ...

    def update_task(self, task: TaskUpdateDTO) -> Task: ...

    def deactivate_task(self, task_id: int) -> None: ...

    def toggle_task_done(self, task_id: int) -> None: ...
